### ISSUE TITLE
Pickup Type & Map Vote 

### ISSUE THREAD

**Issue by drk1590** [SmileYzn/MatchBot#150]
Hello,

We tested out the mod, we have some problem/mistake which need to be fixed. The first one: After the first pick, it started the match.
Second one: After 123% map choose it did not pick the "right" map. Third one: Since the last update the server did not working, Am I having the problem or the mod has something? Fourth one: the commands from the users, not every command can be used. The last mistake is a question: this mod does not have to work like after the pick it has to ask that which map we want to use?

**Comment by SmileYzn** [comment]
Please, try to explain better what is pick mod !!

What is happening with mod, i really did not understand nothing from that issue.

**Comment by drk1590** [comment]
I set this pickup to default leaders mode and the game starts automatically, you know?

Team Pickup Type when match begin
//
// -1 Enable vote
// 0 Leaders
// 1 Random
// 2 None
// 3 Skill Balanced
// 4 Swap Teams
// 5 Knife Round
//
// Default "-1"
mb_team_pick_type "-1"

**Comment by drk1590** [comment]
the plugin doesn't wait until other people have chosen terror or counter, after one choice the search starts

**Comment by drk1590** [comment]
My English is pretty bad, but the mistakes are clear now, aren't they? 🫣🫣

**Comment by SmileYzn** [comment]
Thanks for feedback I will test it

**Comment by drk1590** [comment]
thank you, have a nice day too

**Comment by SmileYzn** [comment]
Did you can test this build?

https://github.com/SmileYzn/MatchBot/actions/runs/12374850837

Ps. I Have fixed the minimum of players to start captain pickup

**Comment by drk1590** [comment]
I'll try tomorrow but unfortunately there are rarely 10 of us but we'll get there.

**Comment by drk1590** [comment]
Segmentation fault server offline

**Comment by SmileYzn** [comment]
Same server with mb_team_pick_type = 0

I'm using Arch Linux!

https://github.com/user-attachments/assets/117ffc5b-5517-4d4f-8411-c0956dff8970

**Comment by SmileYzn** [comment]
Ps. 

Try to install gdb (GNU Debugger) and try to run with -debug parameter on HLDS
That can generate dump files or logs that can help to solve any bug / problem in HLDS or matchbot

**Comment by drk1590** [comment]
[AF] ReGameDLL API minor version mismatch; expected at least 27, real 26
[AF] Please update the ReGameDLL up to a minor version API >= 27

   AMX Mod X version 1.10.0.5461 Copyright (c) 2004-2015 AMX Mod X Development Team
   AMX Mod X comes with ABSOLUTELY NO WARRANTY; for details type `amxx gpl'.
   This is free software and you are welcome to redistribute it under
   certain conditions; type 'amxx gpl' for details.

[ReAuthCheck] Version: 0.1.6 Linux 'Counter-Strike 1.6'
[ReAuthCheck] Success: Configuration executed.
[ReAuthCheck] Success: Build ReHLDS version defined Linux '3378'
[WHB] Version: 1.5.697 Linux (Usage SSE 4.1)
[WHB] Success: Build ReHLDS version defined Linux '3378'
[WHB] Success: Configuration executed.
ReGameDLL version: 5.26.0.668-dev
[ReAimDetector] Version: 0.2.2 Linux 'Counter-Strike 1.6'
[ReAimDetector] Success: Build ReHLDS version defined Linux '3378'.
Executing ReGameDLL Configuration File
Segmentation fault
./hlds_run: 201: gdb: not found
email debug.log to linux@valvesoftware.com
Wed Dec 18 11:52:00 CET 2024: Server restart in 10 seconds

that's all I have :c

**Comment by drk1590** [comment]
if I turn off the matchbot dllst metamod, the server starts immediately

![image](https://github.com/user-attachments/assets/57bc8796-4eac-47ae-9e55-02341191d8f7)

**Comment by SmileYzn** [comment]
Did you try only with matchbot?

Ps.
[AF] ReGameDLL API minor version mismatch; expected at least 27, real 26
[AF] Please update the ReGameDLL up to a minor version API >= 27

**Comment by drk1590** [comment]
Console initialized.
Using breakpad crash handler
Setting breakpad minidump AppID = 10
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 11:45:22 Dec 15 2024 (3900)
STEAM Auth Server
Server IP address 95.138.193.177:27002

   Metamod-r version 1.3.0.131 Copyright (c) 2016-2018 ReHLDS Team (rebuild of original Metamod by Will Day and Jussi Kivilinna)
   Metamod-r comes with ABSOLUTELY NO WARRANTY; for details type `meta gpl'.
   This is free software, and you are welcome to redistribute it
   under certain conditions; type `meta gpl' for details.

Metamod-r v1.3.0.131, API (5:13)
Metamod-r build: 18:51:08 Jul 11 2022
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/adc9414

   AMX Mod X version 1.10.0.5461 Copyright (c) 2004-2015 AMX Mod X Development Team
   AMX Mod X comes with ABSOLUTELY NO WARRANTY; for details type `amxx gpl'.
   This is free software and you are welcome to redistribute it under
   certain conditions; type 'amxx gpl' for details.

[ReAuthCheck] Version: 0.1.6 Linux 'Counter-Strike 1.6'
[ReAuthCheck] Success: Configuration executed.
[ReAuthCheck] Success: Build ReHLDS version defined Linux '3900'
[WHB] Version: 1.5.697 Linux (Usage SSE 4.1)
[WHB] Success: Build ReHLDS version defined Linux '3900'
[WHB] Success: Configuration executed.
ReGameDLL version: 5.28.0.0-dev
[ReAimDetector] Version: 0.2.2 Linux 'Counter-Strike 1.6'
[ReAimDetector] Success: Build ReHLDS version defined Linux '3900'.
Executing ReGameDLL Configuration File
Segmentation fault (core dumped)
./hlds_run: 201: gdb: not found
email debug.log to linux@valvesoftware.com
Wed Dec 18 12:30:19 CET 2024: Server restart in 10 seconds

server is offline

**Comment by SmileYzn** [comment]
Again: try to install gdb and run only with matchbot enabled in metamod.

./hlds_run: 201: gdb: not found

**Comment by drk1590** [comment]
whitout plugins 
Console initialized.
Using breakpad crash handler
Setting breakpad minidump AppID = 10
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 11:45:22 Dec 15 2024 (3900)
STEAM Auth Server
Server IP address 95.138.193.177:27002

   Metamod-r version 1.3.0.131 Copyright (c) 2016-2018 ReHLDS Team (rebuild of original Metamod by Will Day and Jussi Kivilinna)
   Metamod-r comes with ABSOLUTELY NO WARRANTY; for details type `meta gpl'.
   This is free software, and you are welcome to redistribute it
   under certain conditions; type `meta gpl' for details.

Metamod-r v1.3.0.131, API (5:13)
Metamod-r build: 18:51:08 Jul 11 2022
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/adc9414
ReGameDLL version: 5.28.0.0-dev
Executing ReGameDLL Configuration File
Segmentation fault (core dumped)
BFD: warning: /home/mixalap/serverfiles/core is truncated: expected core file size >= 122150912, found: 2998272

warning: Section `.reg-xstate/2749735' in core file too small.

warning: Error reading shared library list entry at 0x74727473

warning: Error reading shared library list entry at 0x6975622e
Failed to read a valid object file image from memory.

warning: Section `.reg-xstate/2749735' in core file too small.
warning: Error reading shared library list entry at 0x74727473
warning: Error reading shared library list entry at 0x6975622e
debug.cmds:4: Error in sourced command file:
Cannot access memory at address 0xfffa42d8
email debug.log to linux@valvesoftware.com
Wed Dec 18 12:45:55 CET 2024: Server restart in 10 second

**Comment by SmileYzn** [comment]
```
Metamod-r v1.3.0.131, API (5:13)
Metamod-r build: 18:51:08 Jul 11 2022
Metamod-r from: https://github.com/rehlds/Metamod-R/commit/adc9414
```

Try to update Metamod-R: https://github.com/rehlds/Metamod-R/releases

Ps. Did server generated debug.log?

Also try to increase ulimit for gdb operations since
```
BFD: warning: /home/mixalap/serverfiles/core is truncated: expected core file size >= 122150912, found: 2998272
```
Something is wrong with it.

While server did not still generate that dumps, i really can´t find real problem with HLDS / Matchbot

**Comment by drk1590** [comment]
I did not receive any logging from the amx or from the server, this logging is also done by LGSM, how can I increase the 
gdb size, but I don't think this problem has been updated meta

Console initialized.
Using breakpad crash handler
Setting breakpad minidump AppID = 10
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 11:45:22 Dec 15 2024 (3900)
STEAM Auth Server
Server IP address 95.138.193.177:27002

   Metamod-r version 1.3.0.149 Copyright (c) 2016-2018 ReHLDS Team (rebuild of original Metamod by Will Day and Jussi Kivilinna)
   Metamod-r comes with ABSOLUTELY NO WARRANTY; for details type `meta gpl'.
   This is free software, and you are welcome to redistribute it
   under certain conditions; type `meta gpl' for details.

Metamod-r v1.3.0.149, API (5:13)
Metamod-r build: 11:31:21 Apr 23 2024
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/603a257
ReGameDLL version: 5.28.0.0-dev
Executing ReGameDLL Configuration File
Segmentation fault (core dumped)
BFD: warning: /home/mixalap/serverfiles/core is truncated: expected core file size >= 122146816, found: 3002368

warning: Section `.reg-xstate/2864335' in core file too small.

warning: Error reading shared library list entry at 0x74727473

warning: Error reading shared library list entry at 0x6975622e
Failed to read a valid object file image from memory.

warning: Section `.reg-xstate/2864335' in core file too small.
warning: Error reading shared library list entry at 0x74727473
warning: Error reading shared library list entry at 0x6975622e
debug.cmds:4: Error in sourced command file:
Cannot access memory at address 0xffcb5808
email debug.log to linux@valvesoftware.com
Wed Dec 18 13:22:27 CET 2024: Server restart in 10 second

**Comment by SmileYzn** [comment]
Try this action build, i removed strip command from makefile that 
https://github.com/SmileYzn/MatchBot/actions/runs/12393001469

And try to update Metamod-R, Matchbot uses updated CSSDK and metamod-sdk from these projects!

**Comment by drk1590** [comment]
Console initialized.
Using breakpad crash handler
Setting breakpad minidump AppID = 10
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 11:45:22 Dec 15 2024 (3900)
STEAM Auth Server
Server IP address 95.138.193.177:27002

   Metamod-r version 1.3.0.149 Copyright (c) 2016-2018 ReHLDS Team (rebuild of original Metamod by Will Day and Jussi Kivilinna)
   Metamod-r comes with ABSOLUTELY NO WARRANTY; for details type `meta gpl'.
   This is free software, and you are welcome to redistribute it
   under certain conditions; type `meta gpl' for details.

Metamod-r v1.3.0.149, API (5:13)
Metamod-r build: 11:31:21 Apr 23 2024
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/603a257
ReGameDLL version: 5.28.0.0-dev
Executing ReGameDLL Configuration File
Segmentation fault (core dumped)
BFD: warning: /home/mixalap/serverfiles/core is truncated: expected core file size >= 122142720, found: 3002368

warning: Section `.reg-xstate/2922690' in core file too small.

warning: Error reading shared library list entry at 0x74727473

warning: Error reading shared library list entry at 0x6975622e
Failed to read a valid object file image from memory.

warning: Section `.reg-xstate/2922690' in core file too small.
warning: Error reading shared library list entry at 0x74727473
warning: Error reading shared library list entry at 0x6975622e
debug.cmds:4: Error in sourced command file:
Cannot access memory at address 0xffe9cf38
email debug.log to linux@valvesoftware.com
Wed Dec 18 13:40:41 CET 2024: Server restart in 10 seconds

**Comment by drk1590** [comment]
it doesn't even start with disabled meta plugins :c

Error: /home/mixalap/serverfiles/engine_i486.so: undefined symbol: SteamGameServer
Unable to load engine, image is corrupt.
BFD: warning: /home/mixalap/serverfiles/core is truncated: expected core file size >= 122142720, found: 3002368

warning: Section `.reg-xstate/2922690' in core file too small.
Failed to read a valid object file image from memory.

warning: Section `.reg-xstate/2922690' in core file too small.
debug.cmds:4: Error in sourced command file:
Cannot access memory at address 0xffe9cf38
email debug.log to linux@valvesoftware.com
Wed Dec 18 13:56:02 CET 2024: Server restart in 10 seconds
Error: /home/mixalap/serverfiles/engine_i486.so: undefined symbol: SteamGameServer
Unable to load engine, image is corrupt.
BFD: warning: /home/mixalap/serverfiles/core is truncated: expected core file size >= 122142720, found: 3002368

warning: Section `.reg-xstate/2922690' in core file too small.
Failed to read a valid object file image from memory.

warning: Section `.reg-xstate/2922690' in core file too small.
debug.cmds:4: Error in sourced command file:
Cannot access memory at address 0xffe9cf38
email debug.log to linux@valvesoftware.com
Wed Dec 18 13:56:13 CET 2024: Server restart in 10 seconds
Error: /home/mixalap/serverfiles/engine_i486.so: undefined symbol: SteamGameServer
Unable to load engine, image is corrupt.
BFD: warning: /home/mixalap/serverfiles/core is truncated: expected core file size >= 122142720, found: 3002368

warning: Section `.reg-xstate/2922690' in core file too small.
Failed to read a valid object file image from memory.

warning: Section `.reg-xstate/2922690' in core file too small.
debug.cmds:4: Error in sourced command file:
Cannot access memory at address 0xffe9cf38
email debug.log to linux@valvesoftware.com
Wed Dec 18 13:56:23 CET 2024: Server restart in 10 seconds
Error: /home/mixalap/serverfiles/engine_i486.so: undefined symbol: SteamGameServer
Unable to load engine, image is corrupt.
BFD: warning: /home/mixalap/serverfiles/core is truncated: expected core file size >= 122142720, found: 3002368

warning: Section `.reg-xstate/2922690' in core file too small.
Failed to read a valid object file image from memory.

warning: Section `.reg-xstate/2922690' in core file too small.
debug.cmds:4: Error in sourced command file:
Cannot access memory at address 0xffe9cf38
email debug.log to linux@valvesoftware.com
Wed Dec 18 13:56:33 CET 2024: Server restart in 10 seconds

**Comment by SmileYzn** [comment]
Fixed!
In final world, the real problem is that match-bot was being compiled with G++ 8, while amxx is being compiled with G++ 4 maybe

![image](https://github.com/user-attachments/assets/82d657cc-c67a-407f-8d8a-b102f1fc1acb)

**Comment by drk1590** [comment]
I updated everything to the stable version, but it's still not good for me :c

      description       stat pend  file                        vers          src  load  unload
 [ 1] Reunion           RUN   -    reunion_mm_i386.so          v0.1.92d      ini  Start Never
 [ 2] <matchbot_mm.so>  badf load  matchbot_mm.so              v -           ini   -     -   
 [ 3] HitBox Fix        RUN   -    hitbox_fix_mm_i386.so       v2.0.3        ini  Start ANY  
 [ 4] Accuracy Fix      RUN   -    accuracyfix_mm.so           v1.1.7        ini  ANY   ANY  
 [ 5] AMX Mod X         RUN   -    amxmodx_mm_i386.so          v1.10.0.5461  ini  Start ANY  
 [ 6] ReAuthCheck       RUN   -    reauthcheck_mm_i386.so      v0.1.6        ini  Start Never
 [ 7] WHBlocker         RUN   -    whblocker_mm_i386.so        v1.5.697      ini  Chlvl ANY  
 [ 8] Fun               RUN   -    fun_amxx_i386.so            v1.10.0.5461  pl5  ANY   ANY  
 [ 9] ReAimDetector     RUN   -    reaimdetector_amxx_i386.so  v0.2.2        pl5  ANY   Never
 [10] FakeMeta          RUN   -    fakemeta_amxx_i386.so       v1.10.0.5461  pl5  ANY   ANY  
 [11] Engine            RUN   -    engine_amxx_i386.so         v1.10.0.5461  pl5  ANY   ANY  
 [12] CStrike           RUN   -    cstrike_amxx_i386.so        v1.10.0.5461  pl5  ANY   ANY  
-

   Metamod-r version 1.3.0.131 Copyright (c) 2016-2018 ReHLDS Team (rebuild of original Metamod by Will Day and Jussi Kivilinna)
   Metamod-r comes with ABSOLUTELY NO WARRANTY; for details type `meta gpl'.
   This is free software, and you are welcome to redistribute it
   under certain conditions; type `meta gpl' for details.
   
Metamod-r v1.3.0.131, API (5:13)
Metamod-r build: 18:51:08 Jul 11 2022
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/adc9414
Loading lib:cs.so

   AMX Mod X version 1.10.0.5461 Copyright (c) 2004-2015 AMX Mod X Development Team 
   AMX Mod X comes with ABSOLUTELY NO WARRANTY; for details type `amxx gpl'.
   This is free software and you are welcome to redistribute it under 
   certain conditions; type 'amxx gpl' for details.
  
[ReAuthCheck] Version: 0.1.6 Linux 'Counter-Strike 1.6'
[ReAuthCheck] Success: Configuration executed.
[ReAuthCheck] Success: Build ReHLDS version defined Linux '3900'
[WHB] Version: 1.5.697 Linux (Usage SSE 4.1)
[WHB] Success: Build ReHLDS version defined Linux '3900'
[WHB] Success: Configuration executed.
ReGameDLL version: 5.28.0.0-dev
[ReAimDetector] Version: 0.2.2 Linux 'Counter-Strike 1.6'
[ReAimDetector] Success: Build ReHLDS version defined Linux '3900'.
Executing ReGameDLL Configuration File 
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
CAppInfoCacheReadFromDiskThread took 4 milliseconds to initialize
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197960265728 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  76561197960265728
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197960265728 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  76561197960265728
Could not find steamerrorreporter binary. Any minidumps will be uploaded in-process
Executing AMX Mod X Configuration File 
Connection to Steam servers successful.
   VAC secure mode is activated.
Rcon from 62.165.212.218:31653:
Currently loaded plugins:
12 plugins, 11 running
quit
Wed Dec 18 19:27:10 CET 2024: Server restart in 10 seconds

**Comment by SmileYzn** [comment]
In this case do these steps:

1. turn on logs "log on" on server.cfg
2. mp_logdetail 3
3. go to metamod config.ini and set debuglevel 42
4. Post results here

And again, update metamod-r

**Comment by drk1590** [comment]
L 12/18/2024 - 19:44:17: [META] ini: Begin re-reading plugins list: /home/mixalap/serverfiles/cstrike/addons/metamod/plugins.ini
L 12/18/2024 - 19:44:17: [META] (debug:8) Looking for loaded plugin with path: /home/mixalap/serverfiles/cstrike/addons/reunion/reunion_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin reunion_mm_i386.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/reunion/reunion_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:8) Found loaded plugin reunion_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:5) newer_file? file=reunion_mm_i386.so; load=1734547403, file=1692091557; ctime=1692091557, mtime=1610034930
L 12/18/2024 - 19:44:17: [META] ini: Read plugin config for: Reunion
L 12/18/2024 - 19:44:17: [META] (debug:8) Looking for loaded plugin with path: /home/mixalap/serverfiles/cstrike/addons/matchbot/dlls/matchbot_mm.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin reunion_mm_i386.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/reunion/reunion_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin matchbot_mm.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/matchbot/dlls/matchbot_mm.so
L 12/18/2024 - 19:44:17: [META] (debug:8) Found loaded plugin matchbot_mm.so
L 12/18/2024 - 19:44:17: [META] (debug:5) newer_file? file=matchbot_mm.so; load=0, file=1734546308; ctime=1734546308, mtime=1734540414
L 12/18/2024 - 19:44:17: [META] ERROR: ini: Plugin '<matchbot_mm.so>' has newer file, but unexpected status (badfile)
L 12/18/2024 - 19:44:17: [META] ini: Read plugin config for: <matchbot_mm.so>
L 12/18/2024 - 19:44:17: [META] (debug:8) Looking for loaded plugin with path: /home/mixalap/serverfiles/cstrike/addons/hitbox_fix/hitbox_fix_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin reunion_mm_i386.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/reunion/reunion_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin matchbot_mm.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/matchbot/dlls/matchbot_mm.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin hitbox_fix_mm_i386.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/hitbox_fix/hitbox_fix_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:8) Found loaded plugin hitbox_fix_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:5) newer_file? file=hitbox_fix_mm_i386.so; load=1734547403, file=1734546283; ctime=1734546283, mtime=1734540414
L 12/18/2024 - 19:44:17: [META] ini: Read plugin config for: HitBox Fix
L 12/18/2024 - 19:44:17: [META] (debug:8) Looking for loaded plugin with path: /home/mixalap/serverfiles/cstrike/addons/accuracyfix/accuracyfix_mm.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin reunion_mm_i386.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/reunion/reunion_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin matchbot_mm.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/matchbot/dlls/matchbot_mm.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin hitbox_fix_mm_i386.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/hitbox_fix/hitbox_fix_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin accuracyfix_mm.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/accuracyfix/accuracyfix_mm.so
L 12/18/2024 - 19:44:17: [META] (debug:8) Found loaded plugin accuracyfix_mm.so
L 12/18/2024 - 19:44:17: [META] (debug:5) newer_file? file=accuracyfix_mm.so; load=1734547403, file=1734546273; ctime=1734546273, mtime=1734540414
L 12/18/2024 - 19:44:17: [META] ini: Read plugin config for: Accuracy Fix
L 12/18/2024 - 19:44:17: [META] (debug:8) Looking for loaded plugin with path: /home/mixalap/serverfiles/cstrike/addons/amxmodx/dlls/amxmodx_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin reunion_mm_i386.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/reunion/reunion_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin matchbot_mm.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/matchbot/dlls/matchbot_mm.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin hitbox_fix_mm_i386.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/hitbox_fix/hitbox_fix_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin accuracyfix_mm.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/accuracyfix/accuracyfix_mm.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin amxmodx_mm_i386.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/amxmodx/dlls/amxmodx_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:8) Found loaded plugin amxmodx_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:5) newer_file? file=amxmodx_mm_i386.so; load=1734547403, file=1734531486; ctime=1734531486, mtime=1638816003
L 12/18/2024 - 19:44:17: [META] ini: Read plugin config for: AMX Mod X
L 12/18/2024 - 19:44:17: [META] (debug:8) Looking for loaded plugin with path: /home/mixalap/serverfiles/cstrike/addons/reauthcheck/reauthcheck_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin reunion_mm_i386.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/reunion/reunion_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin matchbot_mm.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/matchbot/dlls/matchbot_mm.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin hitbox_fix_mm_i386.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/hitbox_fix/hitbox_fix_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin accuracyfix_mm.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/accuracyfix/accuracyfix_mm.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin amxmodx_mm_i386.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/amxmodx/dlls/amxmodx_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin reauthcheck_mm_i386.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/reauthcheck/reauthcheck_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:8) Found loaded plugin reauthcheck_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:5) newer_file? file=reauthcheck_mm_i386.so; load=1734547403, file=1692091556; ctime=1692091556, mtime=1489004857
L 12/18/2024 - 19:44:17: [META] ini: Read plugin config for: ReAuthCheck
L 12/18/2024 - 19:44:17: [META] (debug:8) Looking for loaded plugin with path: /home/mixalap/serverfiles/cstrike/addons/whblocker/whblocker_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin reunion_mm_i386.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/reunion/reunion_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin matchbot_mm.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/matchbot/dlls/matchbot_mm.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin hitbox_fix_mm_i386.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/hitbox_fix/hitbox_fix_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin accuracyfix_mm.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/accuracyfix/accuracyfix_mm.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin amxmodx_mm_i386.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/amxmodx/dlls/amxmodx_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin reauthcheck_mm_i386.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/reauthcheck/reauthcheck_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:9) Looking at: plugin whblocker_mm_i386.so loadedpath: /home/mixalap/serverfiles/cstrike/addons/whblocker/whblocker_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:8) Found loaded plugin whblocker_mm_i386.so
L 12/18/2024 - 19:44:17: [META] (debug:5) newer_file? file=whblocker_mm_i386.so; load=1734547403, file=1692091557; ctime=1692091557, mtime=1588366814
L 12/18/2024 - 19:44:17: [META] ini: Read plugin config for: WHBlocker
L 12/18/2024 - 19:44:17: [META] ini: Finished reading plugins list: /home/mixalap/serverfiles/cstrike/addons/metamod/plugins.ini; Found 7 plugins
L 12/18/2024 - 19:44:17: [META] dll: Updating plugins...
L 12/18/2024 - 19:44:17: [META] (debug:1) Keeping plugin 'Reunion'
L 12/18/2024 - 19:44:17: [META] (debug:1) Loading plugin '<matchbot_mm.so>'
L 12/18/2024 - 19:44:17: [META] ERROR: dll: Failed query plugin '<matchbot_mm.so>'; Couldn't open file '/home/mixalap/serverfiles/cstrike/addons/matchbot/dlls/matchbot_mm.so': /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/mixalap/serverfiles/cstrike/addons/matchbot/dlls/matchbot_mm.so)
L 12/18/2024 - 19:44:17: [META] ERROR: dll: Skipping plugin '<matchbot_mm.so>'; couldn't query
L 12/18/2024 - 19:44:17: [META] ERROR: dll: Couldn't close plugin file 'matchbot_mm.so': invalid handle
L 12/18/2024 - 19:44:17: [META] (debug:1) Keeping plugin 'HitBox Fix'
L 12/18/2024 - 19:44:17: [META] (debug:1) Keeping plugin 'Accuracy Fix'
L 12/18/2024 - 19:44:17: [META] (debug:1) Keeping plugin 'AMX Mod X'
L 12/18/2024 - 19:44:17: [META] (debug:1) Keeping plugin 'ReAuthCheck'
L 12/18/2024 - 19:44:17: [META] (debug:1) Keeping plugin 'WHBlocker'
L 12/18/2024 - 19:44:17: [META] dll: Finished updating 12 plugins; kept 6, loaded 0, unloaded 0, reloaded 0, delayed 0
L 12/18/2024 - 19:44:17: [META] dll: Rebuilding callbacks...
L 12/18/2024 - 19:44:17: [META] dll: Callbacks rebuilded.
L 12/18/2024 - 19:44:17: Log file closed

**Comment by drk1590** [comment]
Debian 11

**Comment by SmileYzn** [comment]
For debian 11 try:
https://github.com/SmileYzn/MatchBot/actions/runs/12405460140

If this not work, i will not setup matchbot to build with github actions anymore, just manual builds

**Comment by drk1590** [comment]
L 12/19/2024 - 06:18:22: [META] ERROR: ini: Plugin '<matchbot_mm.so>' has newer file, but unexpected status (badfile)
L 12/19/2024 - 06:18:22: [META] ERROR: dll: Failed query plugin '<matchbot_mm.so>'; Couldn't open file '/home/mixalap/serverfiles/cstrike/addons/matchbot/dlls/matchbot_mm.so': /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/mixalap/serverfiles/cstrike/addons/matchbot/dlls/matchbot_mm.so)
L 12/19/2024 - 06:18:22: [META] ERROR: dll: Skipping plugin '<matchbot_mm.so>'; couldn't query
L 12/19/2024 - 06:18:22: [META] ERROR: dll: Couldn't close plugin file 'matchbot_mm.so': invalid handle

**Comment by SmileYzn** [comment]
Something is wrong with your install, last action build points to another version of GLIBC

```
[eu@pc Desktop]$ strings matchbot_mm.so | grep LIBC
GLIBC_2.0
GLIBC_2.1.3
GLIBC_2.1
GLIBCXX_3.4.20
GLIBCXX_3.4
```

Please, update to: https://github.com/SmileYzn/MatchBot/actions/runs/12405460140
And shutdown and start server again! a simple restart will not reload plugin correctly

**Comment by drk1590** [comment]
[L1219000.log](https://github.com/user-attachments/files/18198502/L1219000.log)
[L1219001.log](https://github.com/user-attachments/files/18198503/L1219001.log)

**Comment by drk1590** [comment]
meta reload matchbot_mm.so
L 12/19/2024 - 14:29:22: [META] WARNING: dll: Plugin '<matchbot_mm.so>' isn't running; Forcing unload plugin for reloading
L 12/19/2024 - 14:29:22: [META] WARNING: dll: Couldn't close plugin file 'matchbot_mm.so': invalid handle
L 12/19/2024 - 14:29:22: [META] ERROR: Cannot clear plugin '<matchbot_mm.so>'; not marked as failed, empty, or open (status=valid)
L 12/19/2024 - 14:29:22: [META] dll: Unloaded plugin '<matchbot_mm.so>' for reason 'reloading'
L 12/19/2024 - 14:29:22: [META] dll: Rebuilding callbacks...
L 12/19/2024 - 14:29:22: [META] dll: Callbacks rebuilded.
L 12/19/2024 - 14:29:22: [META] ERROR: dll: Failed query plugin '<matchbot_mm.so>'; Couldn't open file 'addons/matchbot/dlls/matchbot_mm.so': addons/matchbot/dlls/matchbot_mm.so: cannot open shared object file: No such file or directory
L 12/19/2024 - 14:29:22: [META] ERROR: dll: Skipping plugin '<matchbot_mm.so>'; couldn't query
L 12/19/2024 - 14:29:22: [META] ERROR: dll: Couldn't close plugin file 'matchbot_mm.so': invalid handle
L 12/19/2024 - 14:29:22: [META] WARNING: dll: Failed to reload plugin '<matchbot_mm.so>' after unloading

**Comment by SmileYzn** [comment]
@drk1590 

The error is very clear about:

```
L 12/19/2024 - 14:29:22: [META] ERROR: dll: Failed query plugin '<matchbot_mm.so>'; Couldn't open file 'addons/matchbot/dlls/matchbot_mm.so': addons/matchbot/dlls/matchbot_mm.so: cannot open shared object file: No such file or directory
```

**Comment by drk1590** [comment]
@SmileYzn 
if everything is true, this was the last update where it still worked for me 
https://github.com/SmileYzn/MatchBot/actions/runs/10836895654

**Comment by SmileYzn** [comment]
Builded with ubuntu 18.04 for now, without crashes 👍

**Comment by drk1590** [comment]
It's still not good for me :c 
warning: Section `.reg-xstate/1108378' in core file too small.

warning: Section `.reg-xstate/1108378' in core file too small.

**Comment by drk1590** [comment]
Could it be that the .so file that is included in the actions is too small?

**Comment by SmileYzn** [comment]
@drk1590

**Comment by SmileYzn** [comment]
Ps. Try to update metamod-r, rehlds + ReGameDLL_CS

**Comment by drk1590** [comment]
ReHLDS version: 3.14.0.0-dev
Build date: 11:45:22 Dec 15 2024 (3900)
AMX Mod X 1.10.0.5461 (http://www.amxmodx.org)
Metamod-r v1.3.0.149, API (5:13)
ReGameDLL version: 5.28.0.0-dev

These work, but my server doesn't work after a major update.

**Comment by SmileYzn** [comment]
Did you can add-me on steam or something else?

Really need more info about that issue 


[ME](https://steamcommunity.com/id/_smiley)

**Comment by drk1590** [comment]
I sent it to see if I could help somehow.

**Comment by SmileYzn** [comment]
As expected, server do not contain legacy binaries, that issue is solved now
