### ISSUE TITLE
ISSUE Changing map when game is live

### ISSUE THREAD

**Issue by yuyiken** [SmileYzn/MatchBot#42]
Hi, I was doing some tests, and when the game is live, if admin changes map from menu. 

In the new map starts votemap instead of chosing captains etc... . 

But if you stop the game first and then change map it dont start votemap.

My suggestion is disable change map in menu when game is live. I think it is fast and good solution.

**Comment by SmileYzn** [comment]
Thanks for testing it!

**Comment by SmileYzn** [comment]
> Hi, I was doing some tests, and when the game is live, if admin changes map from menu.
> 
> In the new map starts votemap instead of chosing captains etc... .
> 
> But if you stop the game first and then change map it dont start votemap.
> 
> My suggestion is disable change map in menu when game is live. I think it is fast and good solution.

Need only to disable votemap in case of admin change it

**Comment by SmileYzn** [comment]
Fixed on https://github.com/SmileYzn/MatchBot/actions/runs/4846569170

**Comment by yuyiken** [comment]
Thank you!

**Comment by yuyiken** [comment]
Still have this bug, downloaded lastest compilation from yesterday. 
https://www.youtube.com/watch?v=CmFM-EvlgGM
